# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72b75c154a20b960af0e3e878be0bd5aa2fd259fc02492d174194a78b937e8dcd0ae0a49e9e7e3c0385a254b89601230135c4a66546884ed024625665ed118cb

test:
  secret_key_base: f790c3532196b7f325da41c748bda6703db72ffc54e304269f7cb7ca7855d5a0041cd5c8b8254d182dec35a4bb6127a265adb218bfe6b91ed1c5f103818b5817

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
